### ISSUE TITLE
I'm being made a suspect even though I'm not using freecam.

### ISSUE THREAD

**Issue by orarange** [Rjlintkh/bdsx-Aniketos#10]
I'm not using freecam, but just a large packet makes me a suspect.

I'm sorry.
I couldn't get a picture.

**Comment by Rjlintkh** [comment]
Currently it only allow clients to stop sending packets within 3 seconds, you could either adjust it in `movement/freecam.js` or just disable freecam as I cant think of an easy way to avoid this :/
