### ISSUE TITLE
I can't get into the server on my Nintendo Switch.

### ISSUE THREAD

**Issue by orarange** [Rjlintkh/bdsx-Aniketos#11]
When I try to enter the server with my Nintendo Switch, 
it recognizes it as toolbox and won't let me in, as shown in the image.
![IMG_0486](https://user-images.githubusercontent.com/81461409/153746324-38ddbf94-a049-46cb-8c03-2786c08a62f0.jpg)

**Comment by Rjlintkh** [comment]
I dont have a nintendo switch so I cannot test, but I tried to fix this in the latest commit
