### ISSUE TITLE
Randomly detected Illegal Item Giving

### ISSUE THREAD

**Issue by bibihool** [Rjlintkh/bdsx-Aniketos#4]
Sometime it kick you with the reason (lllegal Item Giving) for nothing
it happen third time to me and one to my friend (our ping is good)
I dont know how it detected. it happen very few amount of time
just hoping it can be solve

**Comment by bibihool** [comment]
每次被kick都没干什么
我朋友讲,他是向下挖石头的时候被kick
我是走路的时候一直空手按右键被kick
还有一次一直给村民丢马铃薯被kick -__-

**Comment by Rjlintkh** [comment]
With the new update this should be solved.
