### ISSUE TITLE
nuker suspect wrongly

### ISSUE THREAD

**Issue by bibihool** [Rjlintkh/bdsx-Aniketos#9]
![image](https://user-images.githubusercontent.com/72029878/151385882-3d5db07d-a5fc-4054-a5ee-a4434abe3a82.png)
i just get suspect just because i break sand using effienciency 5 shovel with haste 2

**Comment by Rjlintkh** [comment]
I see, this might happen if the server is not fast enough, will add a bypass for efficiency.

**Comment by Rjlintkh** [comment]
It was added in the latest commit
